name: 'xgovw'
description: 'Run xgovw, the xGov validator, as a GitHub action'
inputs:
  token:
    description: 'GitHub Secret Token'
    required: true
  unchecked:
    description: 'xGov numbers (comma separated) that should not be linted'
    required: false
    default: ''
  warning-only:
    description: 'Replace all errors with warnings'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
